version: "3.7"
services:
  db:
    image: "postgres:11.5"
    environment:
      - POSTGRES_USER=deepsight-interview
      - POSTGRES_PASSWORD=deepsight-interview
      - POSTGRES_DB=deepsight-interview-db
    ports:
      - "54321:5432"
    restart: always
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_database:
      external: true
